Repository Malagor/rs-lang, pull requests merged in 2021-03, with the labels that each got.

#4 RSL-03 - feat: add material
  package.json
  public/index.html
  src/appConstants/index.ts
  src/modules/MainPage/actionConst.ts
  src/modules/MainPage/actions.ts
  src/modules/MainPage/mainPageReducer.ts
  src/modules/TextBookPage/actionConst.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/components/WordsList/WordList.tsx
  src/modules/TextBookPage/components/WordsList/styled.ts
  src/modules/TextBookPage/textBookReducer.ts
  yarn.lock
Labels: 🎯 feat, 🛠 refactor

#12 Rsl 06 layout
  README.md
  package.json
  public/favicon.ico
  src/appConstants/colors.ts
  src/appConstants/index.ts
  src/assets/svg/github.svg
  src/assets/svg/rs_school_js.svg
  src/assets/webp/mark-github-512.webp
  src/components/App/App.tsx
  src/components/Layout/Layout.tsx
  src/components/Layout/components/Footer/Footer.tsx
  src/components/Layout/components/Footer/index.ts
  src/components/Layout/components/Footer/styled.ts
  src/components/Layout/components/Header/Header.tsx
  src/components/Layout/components/Header/components/PageTitle/PageTitle.tsx
  src/components/Layout/components/Header/components/PageTitle/index.ts
  src/components/Layout/components/Header/components/index.ts
  src/components/Layout/components/Header/index.ts
  src/components/Layout/components/Header/styled.ts
  src/components/Layout/components/SideBar/SideBar.tsx
  src/components/Layout/components/SideBar/components/SideNav/SideNav.tsx
  src/components/Layout/components/SideBar/components/SideNav/components/LogoutItem/LogoutItem.tsx
  src/components/Layout/components/SideBar/components/SideNav/components/LogoutItem/index.ts
  src/components/Layout/components/SideBar/components/SideNav/components/LogoutItem/styled.ts
  src/components/Layout/components/SideBar/components/SideNav/components/MenuItem/MenuItem.tsx
  src/components/Layout/components/SideBar/components/SideNav/components/MenuItem/index.ts
  src/components/Layout/components/SideBar/components/SideNav/components/MenuItem/styled.ts
  src/components/Layout/components/SideBar/components/SideNav/components/index.ts
  src/components/Layout/components/SideBar/components/SideNav/index.ts
  src/components/Layout/components/SideBar/components/index.ts
  src/components/Layout/components/SideBar/index.ts
  src/components/Layout/components/SideBar/styled.ts
  src/components/Layout/components/index.ts
  src/components/Layout/styled.ts
  src/index.css
  src/modules/GamesPage/GamesPage.tsx
  src/modules/GamesPage/index.ts
  src/modules/MainPage/MainPage.tsx
  src/modules/StatisticsPage/StatisticsPage.tsx
  src/modules/StatisticsPage/index.ts
  src/modules/TextBookPage/TextBookPage.tsx
  src/modules/TextBookPage/components/WordsList/WordList.tsx
  src/modules/TextBookPage/components/WordsList/styled.ts
  src/modules/index.ts
  src/store/commonState/actionConsts.ts
  src/store/commonState/actions.ts
  src/store/commonState/commonReducer.ts
  src/store/commonState/selectors.ts
  src/store/index.tsx
  src/types.ts
  yarn.lock
Labels: 🎯 feat

#14 RSL-06 Layout - refactor: correct PR comments
  src/appConstants/index.ts
  src/components/Layout/components/Footer/Footer.tsx
  src/components/Layout/components/Footer/styled.ts
  src/components/Layout/components/Header/styled.ts
  src/components/Layout/components/SideBar/styled.ts
Labels: 🛠 refactor

#27 RSL-09-1 refactor: made panel sticky
  src/components/Layout/styled.ts
  src/modules/TextBookPage/TextBookPage.tsx
  src/modules/TextBookPage/components/WordsList/WordList.tsx
  src/modules/TextBookPage/components/WordsList/components/NavigationSection/NavigationSection.tsx
  src/modules/TextBookPage/components/WordsList/components/NavigationSection/selectors.ts
  src/modules/TextBookPage/components/WordsList/components/NavigationSection/styled.ts
  src/store/commonState/selectors.ts
Labels: 🛠 refactor

#16 Rsl 04 Word Card
  src/appConstants/colors.ts
  src/modules/TextBookPage/actionConst.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/components/WordCard/WordCard.tsx
  src/modules/TextBookPage/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
  src/modules/TextBookPage/components/WordCard/components/ButtonsBlock/index.ts
  src/modules/TextBookPage/components/WordCard/components/ButtonsBlock/styled.ts
  src/modules/TextBookPage/components/WordCard/components/SentencesBlock/SentencesBlock.tsx
  src/modules/TextBookPage/components/WordCard/components/SentencesBlock/index.ts
  src/modules/TextBookPage/components/WordCard/components/SentencesBlock/styled.ts
  src/modules/TextBookPage/components/WordCard/components/TopPart/TopPart.tsx
  src/modules/TextBookPage/components/WordCard/components/TopPart/index.ts
  src/modules/TextBookPage/components/WordCard/components/TopPart/styled.ts
  src/modules/TextBookPage/components/WordCard/components/index.ts
  src/modules/TextBookPage/components/WordCard/index.ts
  src/modules/TextBookPage/components/WordCard/styled.ts
  src/modules/TextBookPage/components/WordsList/WordList.tsx
  src/modules/TextBookPage/components/WordsList/styled.ts
  src/modules/TextBookPage/selectors.ts
  src/modules/TextBookPage/textBookReducer.ts
  src/types.ts
  tsconfig.json
Labels: 🎯 feat

#18 RSL-11 Pagination Current Page Border Fix
  src/components/Pagination/Pagination.tsx
  src/components/Pagination/index.ts
  src/components/Pagination/styled.tsx
  src/components/index.ts
  src/modules/TextBookPage/TextBookPage.tsx
  src/modules/TextBookPage/components/index.ts
Labels: ❗ fix

#24 RSL-07-1 correct loader size
  src/appConstants/index.ts
  src/components/Loader/styled.tsx
  src/modules/MainPage/MainPage.tsx
Labels: 🛠 refactor

#15 RSL-07 Loader
  src/appConstants/index.ts
  src/components/Loader/Loader.tsx
  src/components/Loader/index.ts
  src/components/Loader/styled.tsx
  src/components/index.ts
  src/modules/MainPage/MainPage.tsx
Labels: 🎯 feat

#31 RSL-18 changed menu Icon, add Dictionary page
  src/components/App/App.tsx
  src/components/Layout/components/SideBar/components/SideNav/SideNav.tsx
  src/modules/DictionaryPage/DictionaryPage.tsx
  src/modules/DictionaryPage/index.ts
  src/modules/index.ts
Labels: 🛠 refactor

#37 RSL-23 Two Paginations Fix
  src/components/Pagination/Pagination.tsx
  src/modules/TextBookPage/TextBookPage.tsx
Labels: ❗ fix

#28 RSL-15 fix: made sidebar sticky
  src/components/Layout/components/SideBar/styled.ts
Labels: ❗ fix, 🛠 refactor

#39 Rsl 17 nav game
  src/appConstants/games.ts
  src/assets/icons/audio.png
  src/assets/icons/ownGame.png
  src/assets/icons/savannah.png
  src/assets/icons/sprint.png
  src/components/App/App.tsx
  src/components/NavGame/NavGame.tsx
  src/components/NavGame/components/GameItem/GameItem.tsx
  src/components/NavGame/components/GameItem/index.ts
  src/components/NavGame/components/GameItem/styled.ts
  src/components/NavGame/components/index.ts
  src/components/NavGame/index.ts
  src/components/NavGame/styled.ts
  src/components/index.ts
  src/modules/AudioChallenge/AudioChallenge.tsx
  src/modules/AudioChallenge/index.ts
  src/modules/DictionaryPage/DictionaryPage.tsx
  src/modules/OwnGame/OwnGame.tsx
  src/modules/OwnGame/index.ts
  src/modules/Savannah/Savannah.tsx
  src/modules/Savannah/index.ts
  src/modules/Sprint/Sprint.tsx
  src/modules/Sprint/index.ts
  src/modules/TextBookPage/components/WordsList/WordList.tsx
  src/modules/index.ts
  src/styles.ts
Labels: 🎯 feat

#46 RSL-28 Add catch error and ErrorMessage Component
  src/assets/images/cat.png
  src/components/ErrorMessage/ErrorMessage.tsx
  src/components/ErrorMessage/index.ts
  src/components/ErrorMessage/styled.ts
  src/components/index.ts
  src/modules/TextBookPage/TextBookPage.tsx
  src/modules/TextBookPage/actionConst.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/components/WordCard/components/TopPart/TopPart.tsx
  src/modules/TextBookPage/components/WordsList/WordList.tsx
  src/modules/TextBookPage/selectors.ts
  src/modules/TextBookPage/textBookReducer.ts
  src/types.ts
Labels: 🎯 feat

#38 RSL 20 Add words to user personal lists
  src/components/App/App.tsx
  src/components/Layout/components/SideBar/components/SideNav/SideNav.tsx
  src/hooks/useIsWordIncluded.ts
  src/modules/Login/actions.ts
  src/modules/Login/selectors.ts
  src/modules/TextBookPage/TextBookPage.tsx
  src/modules/TextBookPage/actionConst.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/components/WordCard/WordCard.tsx
  src/modules/TextBookPage/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
  src/modules/TextBookPage/components/WordCard/components/TopPart/TopPart.tsx
  src/modules/TextBookPage/components/WordCard/components/TopPart/styled.ts
  src/modules/TextBookPage/components/WordCard/styled.ts
  src/modules/TextBookPage/components/WordsList/WordList.tsx
  src/modules/TextBookPage/components/WordsList/components/NoWordsMessage/NoWordsMessage.tsx
  src/modules/TextBookPage/components/WordsList/components/NoWordsMessage/index.ts
  src/modules/TextBookPage/components/WordsList/components/index.ts
  src/modules/TextBookPage/textBookReducer.ts
  src/services/mongodb.ts
  src/types.ts
Labels: 🎯 feat

#49 Rsl 25
  src/modules/TextBookPage/actionConst.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/components/WordCard/WordCard.tsx
  src/modules/TextBookPage/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
  src/modules/TextBookPage/components/WordCard/components/TopPart/TopPart.tsx
  src/modules/TextBookPage/components/WordCard/components/TopPart/styled.ts
  src/modules/TextBookPage/components/WordCard/styled.ts
  src/modules/TextBookPage/components/WordsList/WordList.tsx
  src/modules/TextBookPage/selectors.ts
  src/modules/TextBookPage/textBookReducer.ts
  src/types.ts
Labels: ❗ fix, 🎯 feat, 🛠 refactor

#52 Rsl 09 2
  src/components/GroupSelector/GroupSelector.tsx
  src/components/GroupSelector/components/ButtonGroupSelector/ButtonGroupSelector.tsx
  src/components/GroupSelector/components/ButtonGroupSelector/styled.ts
Labels: 🛠 refactor
