Repository Malagor/rs-lang, pull requests merged in 2021-04, with the labels that each got.

#56 RSL-32 Fullscreen Button
  src/components/FullscreenButton/FullscreenButton.tsx
  src/components/FullscreenButton/index.tsx
  src/components/index.ts
Labels: 🎯 feat

#58 RSL-33 Countdown
  package.json
  src/components/Countdown/Countdown.tsx
  src/components/Countdown/index.ts
  src/components/index.ts
  src/modules/MainPage/MainPage.tsx
  yarn.lock
Labels: 🎯 feat

#61 RSL-34 Sound Button
  src/components/SoundButton/SoundButton.tsx
  src/components/SoundButton/index.ts
  src/components/index.ts
Labels: 🎯 feat

#51 RSL-19 close parts of app for unauthoryzed users
  src/appConstants/games.ts
  src/appConstants/url.ts
  src/assets/images/stop.png
  src/components/App/App.tsx
  src/components/Layout/components/SideBar/components/SideNav/SideNav.tsx
  src/components/RedirectionModal/RedirectionModal.tsx
  src/components/RedirectionModal/index.ts
  src/components/RedirectionModal/styled.ts
  src/components/index.ts
  src/modules/StatisticsPage/StatisticsPage.tsx
Labels: 🎯 feat

#54 RSL-31 frestricted access mark in menu
  src/components/Layout/components/SideBar/components/SideNav/SideNav.tsx
  src/components/Layout/components/SideBar/components/SideNav/components/MenuItem/MenuItem.tsx
  src/modules/DictionaryPage/DictionaryPage.tsx
  src/modules/GamesPage/GamesPage.tsx
  src/modules/Sprint/Sprint.tsx
  src/modules/StatisticsPage/StatisticsPage.tsx
Labels: 🎯 feat

#47 RSL-16 create layout game page 🎯 feat
  src/appConstants/games.ts
  src/modules/GamesPage/GamesPage.tsx
  src/modules/GamesPage/components/GameCard/GameCard.tsx
  src/modules/GamesPage/components/GameCard/index.ts
  src/modules/GamesPage/components/GameCard/styled.ts
  src/modules/GamesPage/components/index.ts
  src/modules/GamesPage/styled.ts
Labels: 🎯 feat

#23 RSL-09 Navigation through the sections of the tutorial 🎯 feat
  src/appConstants/index.ts
  src/components/App/App.tsx
  src/components/GroupSelector/GroupSelector.tsx
  src/components/GroupSelector/components/ButtonGroupSelector/ButtonGroupSelector.tsx
  src/components/GroupSelector/components/ButtonGroupSelector/index.ts
  src/components/GroupSelector/components/ButtonGroupSelector/styled.ts
  src/components/GroupSelector/components/index.ts
  src/components/GroupSelector/index.ts
  src/components/GroupSelector/styled.ts
  src/components/Layout/styled.ts
  src/components/Pagination/styled.tsx
  src/modules/TextBookPage/TextBookPage.tsx
  src/modules/TextBookPage/components/WordCard/styled.ts
  src/modules/TextBookPage/components/WordsList/WordList.tsx
  src/modules/TextBookPage/components/WordsList/styled.ts
  src/modules/TextBookPage/styled.ts
  src/services/localStorage.ts
  src/store/commonState/selectors.ts
Labels: 🎯 feat

#65 RSL-35 fix: correct style for menu item for unauthorized user
  src/components/Layout/components/SideBar/components/SideNav/components/MenuItem/MenuItem.tsx
Labels: ❗ fix

#59 RSL-24 Statistics
  .eslintrc
  package.json
  src/appConstants/games.ts
  src/components/CircularProgressBar/CircularProgressBar.tsx
  src/components/CircularProgressBar/index.ts
  src/modules/GamesPage/GamesPage.tsx
  src/modules/StatisticsPage/StatisticsPage.tsx
  src/modules/StatisticsPage/actionConst.ts
  src/modules/StatisticsPage/actions.ts
  src/modules/StatisticsPage/components/AllTimeBlock/AllTimeBlock.tsx
  src/modules/StatisticsPage/components/AllTimeBlock/components/Graph/Graph.tsx
  src/modules/StatisticsPage/components/AllTimeBlock/components/Graph/index.ts
  src/modules/StatisticsPage/components/AllTimeBlock/components/Graph/styled.ts
  src/modules/StatisticsPage/components/AllTimeBlock/index.ts
  src/modules/StatisticsPage/components/AllTimeBlock/styled.ts
  src/modules/StatisticsPage/components/TodayBlock/TodayBlock.tsx
  src/modules/StatisticsPage/components/TodayBlock/components/Accuracy/Accuracy.tsx
  src/modules/StatisticsPage/components/TodayBlock/components/Accuracy/index.ts
  src/modules/StatisticsPage/components/TodayBlock/components/Accuracy/styled.ts
  src/modules/StatisticsPage/components/TodayBlock/components/GameBlock/GameBlock.tsx
  src/modules/StatisticsPage/components/TodayBlock/components/GameBlock/index.ts
  src/modules/StatisticsPage/components/TodayBlock/components/GameBlock/styled.ts
  src/modules/StatisticsPage/components/TodayBlock/components/LearnedWords/LearnedWords.tsx
  src/modules/StatisticsPage/components/TodayBlock/components/LearnedWords/index.ts
  src/modules/StatisticsPage/components/TodayBlock/components/LearnedWords/styled.ts
  src/modules/StatisticsPage/components/TodayBlock/components/index.ts
  src/modules/StatisticsPage/components/TodayBlock/index.ts
  src/modules/StatisticsPage/components/TodayBlock/styled.ts
  src/modules/StatisticsPage/components/index.ts
  src/modules/StatisticsPage/selectors.ts
  src/modules/StatisticsPage/statisticsReducer.ts
  src/modules/StatisticsPage/styled.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/components/WordCard/WordCard.tsx
  src/modules/TextBookPage/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
  src/modules/TextBookPage/components/WordCard/components/TopPart/TopPart.tsx
  src/services/mongodb.ts
  src/store/index.tsx
  src/types.ts
  yarn.lock
Labels: 🎯 feat

#68 RSL-36 fix menu button and add dynamic setting isMobile
  src/components/Layout/Layout.tsx
  src/components/Layout/components/Header/Header.tsx
  src/components/Layout/components/Header/components/PageTitle/PageTitle.tsx
  src/components/Layout/components/Header/components/PageTitle/styled.ts
  src/components/Layout/components/Header/styled.ts
  src/components/Layout/components/SideBar/SideBar.tsx
  src/components/Layout/components/SideBar/styled.ts
  src/components/Layout/styled.ts
  src/hooks/useIsMobile.ts
Labels: ❗ fix, 🛠 refactor

#44 RSL-27 Game Result Modal
  src/appConstants/colors.ts
  src/appConstants/games.ts
  src/components/GameResults/GameResults.tsx
  src/components/GameResults/index.ts
  src/components/GameResults/styled.ts
  src/components/index.ts
  src/modules/GamesPage/GamesPage.tsx
  src/modules/Savannah/Savannah.tsx
  yarn.lock
Labels: 🎯 feat

#70 RSL-38 Loader With Position: Fixed
  src/components/Loader/Loader.tsx
  src/components/Loader/styled.tsx
  src/modules/MainPage/MainPage.tsx
Labels: ❗ fix

#71 RLS-13 login form validation
  package.json
  src/appConstants/index.ts
  src/components/Layout/components/Header/components/LoginModal/LoginModal.tsx
  src/components/Layout/components/Header/components/LoginModal/components/Form/Form.tsx
  src/components/Layout/components/Header/components/LoginModal/components/Form/index.ts
  src/components/Layout/components/Header/components/LoginModal/components/Form/styled.ts
  src/components/Layout/components/Header/components/LoginModal/components/index.ts
  src/components/Layout/components/Header/components/LoginModal/index.ts
  yarn.lock
Labels: 🎯 feat

#76 RSL-41
  src/appConstants/colors.ts
  src/appConstants/games.ts
  src/components/GameResults/GameResults.tsx
  src/modules/Savannah/Savannah.tsx
Labels: ❗ fix

#77 RSL-40 feat: removed the lock from menu items for unauthorized user
  src/components/Layout/components/SideBar/components/SideNav/SideNav.tsx
  src/modules/DictionaryPage/DictionaryPage.tsx
  src/modules/GamesPage/GamesPage.tsx
  src/modules/StatisticsPage/StatisticsPage.tsx
Labels: 🎯 feat, 🛠 refactor

#86 RSL-46 Game Results Modal: Word Uniqueness Bug Fix
  src/components/GameResults/GameResults.tsx
Labels: ❗ fix

#91 RSL-48 fix: add the check loading userId for Dictionary
  src/modules/DictionaryPage/DictionaryPage.tsx
  src/modules/Login/actionConsts.ts
  src/modules/Login/actions.ts
  src/modules/Login/loginReducer.ts
  src/modules/Login/selectors.ts
  src/types.ts
Labels: ❗ fix, 🛠 refactor

#93 RSL-49 Game Results Modal: Close On Button Click Only
  src/components/GameResults/GameResults.tsx
Labels: ❗ fix

#79 RSL-12 user Avatar
  src/appConstants/index.ts
  src/components/Layout/components/Header/components/LoginModal/LoginModal.tsx
  src/components/Layout/components/Header/components/LoginModal/components/Form/Form.tsx
  src/components/Layout/components/Header/components/LoginModal/components/Form/components/FileInput/FileInput.tsx
  src/components/Layout/components/Header/components/LoginModal/components/Form/components/FileInput/index.ts
  src/components/Layout/components/Header/components/LoginModal/components/Form/components/FileInput/styled.ts
  src/components/Layout/components/Header/components/LoginModal/components/Form/components/index.ts
  src/components/Layout/components/Header/components/LoginModal/components/Form/styled.ts
Labels: 🎯 feat

#96 RSL-30-1 Rearranged blocks on the page
  src/components/Layout/styled.ts
  src/components/NavGame/components/GameItem/styled.ts
  src/components/NavGame/styled.ts
  src/components/Pagination/styled.tsx
  src/modules/DictionaryPage/DictionaryPage.tsx
  src/modules/DictionaryPage/components/Sections/styled.ts
  src/modules/TextBookPage/TextBookPage.tsx
  src/modules/TextBookPage/styled.ts
Labels: 🛠 refactor

#88 RSL-42 Save games results to statistics
  src/modules/GamesPage/saveGameResults.ts
  src/modules/Imaginarium/Imaginarium.tsx
  src/modules/StatisticsPage/StatisticsPage.tsx
  src/modules/StatisticsPage/actions.ts
  src/modules/StatisticsPage/components/TodayBlock/TodayBlock.tsx
  src/modules/StatisticsPage/components/TodayBlock/components/GameBlock/GameBlock.tsx
  src/modules/StatisticsPage/components/TodayBlock/components/LearnedWords/LearnedWords.tsx
  src/modules/StatisticsPage/selectors.ts
  src/modules/StatisticsPage/statisticsReducer.ts
  src/modules/StatisticsPage/styled.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
  src/store/index.tsx
  src/types.ts
Labels: 🎯 feat

#98 Rsl 43 tests
  src/components/App/App.test.tsx
  src/components/NavGame/components/GameItem/GameItem.tsx
  src/modules/Login/login.test.ts
  src/modules/StatisticsPage/statistics.test.ts
  src/modules/TextBookPage/TextBook.test.ts
  yarn.lock
Labels: 🎯 feat

#62 Rsl 30 dictionary
  src/appConstants/index.ts
  src/components/Layout/components/Header/components/PageTitle/PageTitle.tsx
  src/components/Layout/components/Header/components/PageTitle/styled.ts
  src/components/Layout/styled.ts
  src/components/NavGame/components/GameItem/styled.ts
  src/components/NavGame/styled.ts
  src/components/Pagination/styled.tsx
  src/components/WordCard/WordCard.tsx
  src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
  src/components/WordCard/components/ButtonsBlock/index.ts
  src/components/WordCard/components/ButtonsBlock/styled.ts
  src/components/WordCard/components/SentencesBlock/SentencesBlock.tsx
  src/components/WordCard/components/SentencesBlock/index.ts
  src/components/WordCard/components/SentencesBlock/styled.ts
  src/components/WordCard/components/TopPart/TopPart.tsx
  src/components/WordCard/components/TopPart/index.ts
  src/components/WordCard/components/TopPart/styled.ts
  src/components/WordCard/components/index.ts
  src/components/WordCard/index.ts
  src/components/WordCard/styled.ts
  src/components/WordsList/WordList.tsx
  src/components/WordsList/components/NoWordsMessage/NoWordsMessage.tsx
  src/components/WordsList/components/NoWordsMessage/index.ts
  src/components/WordsList/components/index.ts
  src/components/WordsList/index.ts
  src/components/WordsList/styled.ts
  src/components/index.ts
  src/helpers/dictionaryHelpers.ts
  src/modules/DictionaryPage/DictionaryPage.tsx
  src/modules/DictionaryPage/components/Sections/Sections.tsx
  src/modules/DictionaryPage/components/Sections/index.ts
  src/modules/DictionaryPage/components/Sections/styled.ts
  src/modules/DictionaryPage/components/StatisticModal/StatisticModal.tsx
  src/modules/DictionaryPage/components/StatisticModal/components/DialogTitle/DialogTitle.tsx
  src/modules/DictionaryPage/components/StatisticModal/components/DialogTitle/index.ts
  src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/ModalContent.tsx
  src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/index.ts
  src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/styled.ts
  src/modules/DictionaryPage/components/StatisticModal/components/index.ts
  src/modules/DictionaryPage/components/StatisticModal/index.ts
  src/modules/DictionaryPage/components/StatisticModal/styled.ts
  src/modules/DictionaryPage/components/index.ts
  src/modules/DictionaryPage/styled.ts
  src/modules/TextBookPage/TextBookPage.tsx
  src/modules/TextBookPage/actionConst.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/components/WordsList/WordList.tsx
  src/modules/TextBookPage/components/index.ts
  src/modules/TextBookPage/selectors.ts
  src/modules/TextBookPage/styled.ts
  src/modules/TextBookPage/textBookReducer.ts
  src/types.ts
Labels: 🎯 feat

#102 RSL-02 Main page
  package.json
  src/appConstants/colors.ts
  src/appConstants/index.ts
  src/assets/animations/main-dont-forget.json
  src/assets/animations/main-hero.json
  src/assets/svg/rs_school_js.svg
  src/components/GameResults/styled.ts
  src/components/Layout/components/Footer/Footer.tsx
  src/components/Layout/components/Footer/styled.ts
  src/components/Layout/components/Header/components/LoginModal/LoginModal.tsx
  src/components/Layout/components/Header/components/LoginModal/components/Form/Form.tsx
  src/modules/MainPage/MainPage.tsx
  src/modules/MainPage/components/Advantages/Advantages.tsx
  src/modules/MainPage/components/Advantages/index.ts
  src/modules/MainPage/components/Advantages/styled.ts
  src/modules/MainPage/components/OurTeam/OurTeam.tsx
  src/modules/MainPage/components/OurTeam/components/OurTeamCard/OurTeamCard.tsx
  src/modules/MainPage/components/OurTeam/components/OurTeamCard/index.ts
  src/modules/MainPage/components/OurTeam/components/OurTeamCard/styled.ts
  src/modules/MainPage/components/OurTeam/index.ts
  src/modules/MainPage/components/OurTeam/styled.ts
  src/modules/MainPage/styled.ts
  src/store/commonState/actionConsts.ts
  src/store/commonState/actions.ts
  src/store/commonState/commonReducer.ts
  src/store/commonState/selectors.ts
  src/types.ts
  yarn.lock
Labels: 🎯 feat

#104 RSL-56 correct styles of the game buttons wrapper
  src/components/NavGame/styled.ts
Labels: 🛠 refactor

#108 RSL-58 Add learning words logic
  src/appConstants/index.ts
  src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
  src/components/WordsList/WordList.tsx
  src/modules/DictionaryPage/DictionaryPage.tsx
  src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/ModalContent.tsx
  src/modules/GamesPage/saveGameResults.ts
  src/modules/TextBookPage/TextBookPage.tsx
  src/modules/TextBookPage/actionConst.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/selectors.ts
  src/modules/TextBookPage/textBookReducer.ts
  src/types.ts
Labels: 🎯 feat

#106 RSL-57 fix sidebar marker after page reload
  src/components/Layout/components/SideBar/components/SideNav/SideNav.tsx
  src/components/Layout/components/SideBar/components/SideNav/components/MenuItem/MenuItem.tsx
  src/components/Layout/components/SideBar/components/SideNav/components/MenuItem/styled.ts
Labels: ❗ fix

#111 RSL-21 Reload same page
  src/components/App/App.tsx
  src/components/GroupSelector/GroupSelector.tsx
  src/components/Pagination/Pagination.tsx
  src/components/WordCard/WordCard.tsx
  src/components/WordCard/components/ButtonsBlock/ButtonsBlock.tsx
  src/components/WordsList/WordList.tsx
  src/modules/DictionaryPage/DictionaryPage.tsx
  src/modules/TextBookPage/TextBookPage.tsx
  src/modules/TextBookPage/actionConst.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/selectors.ts
  src/modules/TextBookPage/textBookReducer.ts
  src/services/localStorage.ts
  src/types.ts
Labels: 🎯 feat

#114 RSL-55 add deploy settings to firebase
  .firebaserc
  firebase.json
Labels: 🎯 feat

#116 RSL-59 fix deleting words
  src/modules/TextBookPage/actions.ts
Labels: ❗ fix

#123 fix: add case SET_SOUND into reducer for correct playing sound
  src/modules/TextBookPage/textBookReducer.ts
Labels: ❗ fix

#120 RSL-60: Game Title And Return Button On Choose Difficulty Screen
  src/modules/GamesPage/GamesPage.tsx
  src/modules/GamesPage/components/ChooseDifficulty/ChooseDifficulty.tsx
  src/modules/GamesPage/components/ChooseDifficulty/styled.ts
  src/modules/GamesPage/components/GameCard/GameCard.tsx
  src/types.ts
Labels: 🎯 feat

#124 RSL-44-1 Save settings to local storage
  src/components/GameResults/styled.ts
  src/components/Layout/components/Header/components/PageTitle/PageTitle.tsx
  src/components/Layout/components/Header/components/PageTitle/components/TextBookSettings/TextBookSettings.tsx
  src/components/Layout/components/Header/components/PageTitle/components/TextBookSettings/styled.ts
  src/components/Layout/components/Header/components/PageTitle/styled.ts
  src/components/WordCard/WordCard.tsx
  src/components/WordCard/components/SentencesBlock/SentencesBlock.tsx
  src/components/WordCard/components/TopPart/TopPart.tsx
  src/components/WordsList/WordList.tsx
  src/modules/TextBookPage/actionConst.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/selectors.ts
  src/modules/TextBookPage/textBookReducer.ts
  src/services/localStorage.ts
  src/types.ts
Labels: 🎯 feat

#126 RSL-63 Scroll to top after route change
  src/components/App/App.module.scss
  src/components/App/App.tsx
Labels: 🎯 feat

#109 Rsl 44 settings textbook and dictionary
  src/components/GameResults/styled.ts
  src/components/Layout/components/Header/components/PageTitle/PageTitle.tsx
  src/components/Layout/components/Header/components/PageTitle/components/TextBookSettings/TextBookSettings.tsx
  src/components/Layout/components/Header/components/PageTitle/components/TextBookSettings/index.ts
  src/components/Layout/components/Header/components/PageTitle/components/TextBookSettings/styled.ts
  src/components/Layout/components/Header/components/PageTitle/components/index.ts
  src/components/Layout/components/Header/components/PageTitle/styled.ts
  src/components/WordCard/WordCard.tsx
  src/components/WordCard/components/SentencesBlock/SentencesBlock.tsx
  src/components/WordCard/components/TopPart/TopPart.tsx
  src/components/WordsList/WordList.tsx
  src/modules/DictionaryPage/DictionaryPage.tsx
  src/modules/TextBookPage/TextBookPage.tsx
  src/modules/TextBookPage/actionConst.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/selectors.ts
  src/modules/TextBookPage/textBookReducer.ts
  src/services/localStorage.ts
  src/types.ts
Labels: 🎯 feat

#129 RSL-64 Optimize group selector
  src/components/GroupSelector/styled.ts
  src/hooks/useIsPageTopMatch.ts
  src/modules/DictionaryPage/DictionaryPage.tsx
  src/modules/TextBookPage/TextBookPage.tsx
Labels: 🛠 refactor

#121 Rsl 54 statistics modal
  src/components/Layout/components/Header/components/PageTitle/PageTitle.tsx
  src/components/WordsList/WordList.tsx
  src/modules/DictionaryPage/components/StatisticModal/StatisticModal.tsx
  src/modules/DictionaryPage/components/StatisticModal/components/DialogTitle/DialogTitle.tsx
  src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/ModalContent.tsx
  src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/components/Accuracy/Accuracy.tsx
  src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/components/Accuracy/index.ts
  src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/components/Accuracy/styled.ts
  src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/components/index.ts
  src/modules/DictionaryPage/components/StatisticModal/components/ModalContent/styled.ts
  src/modules/DictionaryPage/components/StatisticModal/styled.ts
  src/modules/TextBookPage/actionConst.ts
  src/modules/TextBookPage/actions.ts
  src/modules/TextBookPage/selectors.ts
  src/modules/TextBookPage/textBookReducer.ts
  src/types.ts
Labels: 🎯 feat

#119 RSL-61 docs: fill README.md
  README.md
Labels: 📃 doc

#132 RSL-65 main page info
  .firebase/hosting.YnVpbGQ.cache
  src/appConstants/index.ts
  src/assets/images/liza.jpg
  src/assets/images/vadim.jpg
  src/modules/MainPage/MainPage.tsx
  src/modules/MainPage/components/Advantages/Advantages.tsx
Labels: 🎯 feat

#87 Rsl 29 audiogame
  package.json
  src/appConstants/colors.ts
  src/appConstants/games.ts
  src/components/Layout/components/Header/Header.tsx
  src/components/Layout/components/Header/styled.ts
  src/components/RoundProgressBar/RoundProgressBar.tsx
  src/components/RoundProgressBar/index.ts
  src/components/RoundProgressBar/styled.ts
  src/components/WordCard/components/TopPart/styled.ts
  src/components/WordCard/styled.ts
  src/components/index.ts
  src/helpers/mixingArray.ts
  src/hooks/useBackgroundPage.ts
  src/modules/AudioChallenge/AudioChallenge.tsx
  src/modules/AudioChallenge/components/AudioCard/AudioCard.tsx
  src/modules/AudioChallenge/components/AudioCard/components/Answers/Answers.tsx
  src/modules/AudioChallenge/components/AudioCard/components/Answers/components/AnswerRadio/AnswerRadio.tsx
  src/modules/AudioChallenge/components/AudioCard/components/Answers/components/AnswerRadio/index.ts
  src/modules/AudioChallenge/components/AudioCard/components/Answers/components/AnswerRadio/styled.ts
  src/modules/AudioChallenge/components/AudioCard/components/Answers/components/index.ts
  src/modules/AudioChallenge/components/AudioCard/components/Answers/index.ts
  src/modules/AudioChallenge/components/AudioCard/components/Answers/styled.ts
  src/modules/AudioChallenge/components/AudioCard/components/Question/Question.tsx
  src/modules/AudioChallenge/components/AudioCard/components/Question/index.ts
  src/modules/AudioChallenge/components/AudioCard/components/Question/styled.ts
  src/modules/AudioChallenge/components/AudioCard/components/index.ts
  src/modules/AudioChallenge/components/AudioCard/index.ts
  src/modules/AudioChallenge/components/AudioCard/styled.ts
  src/modules/AudioChallenge/components/NextButton/NextButton.tsx
  src/modules/AudioChallenge/components/NextButton/index.ts
  src/modules/AudioChallenge/components/NextButton/styled.ts
  src/modules/AudioChallenge/components/index.ts
  src/modules/AudioChallenge/styled.ts
  src/store/index.tsx
  src/styles.ts
  yarn.lock
Labels: 🎯 feat

#128 RSL-52 Savannah game
  .eslintrc
  public/index.html
  src/appConstants/colors.ts
  src/appConstants/games.ts
  src/assets/animations/growing-plant.json
  src/modules/AudioChallenge/components/NextButton/styled.ts
  src/modules/GamesPage/components/ChooseDifficulty/styled.ts
  src/modules/Imaginarium/components/Dashboard/styled.ts
  src/modules/Savannah/Savannah.tsx
  src/modules/Savannah/components/Lives/Lives.tsx
  src/modules/Savannah/components/Lives/index.ts
  src/modules/Savannah/components/Lives/styled.ts
  src/modules/Savannah/components/SavannahCard/SavannahCard.tsx
  src/modules/Savannah/components/SavannahCard/components/Answers/Answers.tsx
  src/modules/Savannah/components/SavannahCard/components/Answers/components/AnswerRadio/AnswerRadio.tsx
  src/modules/Savannah/components/SavannahCard/components/Answers/components/AnswerRadio/index.ts
  src/modules/Savannah/components/SavannahCard/components/Answers/components/AnswerRadio/styled.ts
  src/modules/Savannah/components/SavannahCard/components/Answers/components/index.ts
  src/modules/Savannah/components/SavannahCard/components/Answers/index.ts
  src/modules/Savannah/components/SavannahCard/components/Answers/styled.ts
  src/modules/Savannah/components/SavannahCard/components/Question/Question.tsx
  src/modules/Savannah/components/SavannahCard/components/Question/index.ts
  src/modules/Savannah/components/SavannahCard/components/Question/styled.ts
  src/modules/Savannah/components/SavannahCard/components/index.ts
  src/modules/Savannah/components/SavannahCard/index.ts
  src/modules/Savannah/components/SavannahCard/styled.ts
  src/modules/Savannah/components/index.ts
  src/modules/Savannah/styled.ts
Labels: 🎯 feat

#135 RSL-67: Minigame Descriptions
  src/appConstants/games.ts
Labels: ❗ fix

#141 RSL-70 Fix mobile menu
  src/hooks/useIsMobile.ts
Labels: ❗ fix

#139 RSL-69 feat: correct deploy settings
  .firebase/hosting.YnVpbGQ.cache
  firebase.json
Labels: ❗ fix, 🛠 refactor

#136 RSL-50-1 feat: save statistics, load word for game, correct PR comments
  src/appConstants/games.ts
  src/helpers/saveStatistics.ts
  src/modules/Sprint/Sprint.tsx
  src/modules/Sprint/components/PlayPage/PlayPage.tsx
  src/modules/Sprint/components/PlayPage/styled.ts
Labels: 🎯 feat, 🔥 hot-hot-hot 🔥, 🛠 refactor

#142 Rsl 50 Sprint Game
  src/appConstants/games.ts
  src/helpers/saveStatistics.ts
  src/modules/AudioChallenge/components/AudioCard/components/Answers/Answers.tsx
  src/modules/Savannah/components/Lives/Lives.tsx
  src/modules/Savannah/components/SavannahCard/SavannahCard.tsx
  src/modules/Sprint/Sprint.tsx
  src/modules/Sprint/components/PlayPage/PlayPage.tsx
  src/modules/Sprint/components/PlayPage/index.ts
  src/modules/Sprint/components/PlayPage/styled.ts
  src/modules/Sprint/components/index.ts
  src/modules/Sprint/styled.ts
Labels: 🎯 feat

#146 RSL-72 fix counting chain in Savannah
  src/modules/AudioChallenge/AudioChallenge.tsx
  src/modules/Savannah/Savannah.tsx
Labels: ❗ fix

#144 RSL-71 Change styles Sprint
  src/modules/Sprint/Sprint.tsx
  src/modules/Sprint/components/PlayPage/PlayPage.tsx
  src/modules/Sprint/components/PlayPage/styled.ts
Labels: ❗ fix

#148 RSL-73 replace animation on main page with static images
  src/assets/animations/main-dont-forget.json
  src/assets/animations/main-hero.json
  src/assets/svg/main-dont-forget.svg
  src/assets/svg/main-hero.svg
  src/modules/MainPage/MainPage.tsx
  src/modules/MainPage/styled.ts
Labels: 🛠 refactor

#150 RSK-74 Added meta data in the OpenCard format
  public/index.html
  public/rslang-image.jpg
Labels: 🎯 feat
